export const AGENT_ISSUE_CONSOLE_HTML = `<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="light">
  <title>Agent Issue Console</title>
  <style>
    :root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;color:#182321;background:#f3f7f4;--ink:#182321;--muted:#66736f;--line:#dce5e0;--card:#fff;--brand:#147d64;--brand2:#e2f4ec;--danger:#b53a3a;--warn:#a76713;--shadow:0 12px 32px rgba(22,49,41,.08)}
    *{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 85% 0,#dff3e9 0,transparent 32%),#f3f7f4}button,input{font:inherit}button{cursor:pointer}.shell{max-width:1240px;margin:auto;padding:28px}.top{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:24px}.brand{display:flex;gap:12px;align-items:center}.mark{width:42px;height:42px;border-radius:13px;background:#163c32;color:white;display:grid;place-items:center;font-weight:800}.brand h1{font-size:20px;margin:0}.brand p{font-size:13px;color:var(--muted);margin:3px 0 0}.repo{border:1px solid var(--line);background:rgba(255,255,255,.8);padding:9px 12px;border-radius:10px;font-size:13px}.tabs{display:flex;gap:6px;margin-bottom:18px}.tab{border:0;background:transparent;color:var(--muted);padding:9px 13px;border-radius:9px}.tab[aria-selected=true]{color:var(--ink);background:white;box-shadow:var(--shadow)}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:18px}.metric{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:16px;box-shadow:var(--shadow)}.metric span{display:block;color:var(--muted);font-size:12px}.metric strong{display:block;font-size:28px;margin-top:5px}.layout{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(300px,.8fr);gap:18px}.panel{background:var(--card);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow);overflow:hidden}.panel-head{display:flex;align-items:center;justify-content:space-between;padding:16px 18px;border-bottom:1px solid var(--line)}.panel-head h2{font-size:15px;margin:0}.refresh{border:1px solid var(--line);background:white;border-radius:9px;padding:7px 10px;color:var(--ink)}.empty{padding:52px 24px;text-align:center;color:var(--muted)}.empty svg{width:42px;height:42px;color:#91a79f}.empty h3{color:var(--ink);font-size:16px;margin:14px 0 6px}.empty p{font-size:13px;line-height:1.55;margin:0}.chat{padding:18px}.bubble{background:var(--brand2);border-radius:14px 14px 4px 14px;padding:13px 14px;font-size:14px;line-height:1.5;margin-left:32px}.state{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px;margin:14px 2px}.dot{width:8px;height:8px;border-radius:50%;background:var(--brand);box-shadow:0 0 0 4px var(--brand2)}.composer{display:flex;gap:8px;border:1px solid var(--line);padding:7px;border-radius:12px;background:#fafcfb}.composer input{border:0;outline:0;background:transparent;min-width:0;flex:1;padding:8px}.send{border:0;background:var(--brand);color:white;border-radius:9px;padding:8px 13px;font-weight:650}.evidence{margin-top:14px;border-top:1px solid var(--line);padding-top:14px}details{font-size:12px;color:var(--muted)}summary{cursor:pointer;color:var(--ink)}.pill{display:inline-flex;align-items:center;border-radius:999px;background:#edf2ef;padding:5px 8px;font-size:11px;color:var(--muted)}
    @media(max-width:840px){.shell{padding:16px}.top{align-items:flex-start;flex-direction:column}.summary{grid-template-columns:repeat(2,1fr)}.summary .metric:last-child{grid-column:span 2}.layout{grid-template-columns:1fr}.repo{width:100%}.chat-panel{order:-1}}
  </style>
</head>
<body>
  <main class="shell">
    <header class="top"><div class="brand"><div class="mark" aria-hidden="true">AI</div><div><h1>Agent Issue Console</h1><p>調査済みIssueの作成とcodex-loop監視</p></div></div><div class="repo" aria-label="対象repository">ishii1648/agent-issue-console</div></header>
    <nav class="tabs" aria-label="画面"><button class="tab" aria-selected="true">Monitor</button><button class="tab" aria-selected="false">調査履歴</button></nav>
    <section class="summary" aria-label="状態サマリー">
      <article class="metric"><span>着手待ち</span><strong data-count="ready">0</strong></article><article class="metric"><span>実行中</span><strong data-count="running">0</strong></article><article class="metric"><span>回答待ち</span><strong data-count="needs_input">0</strong></article><article class="metric"><span>失敗</span><strong data-count="failed">0</strong></article><article class="metric"><span>完了</span><strong data-count="done">0</strong></article>
    </section>
    <section class="layout">
      <article class="panel"><header class="panel-head"><h2>Issueキュー</h2><button class="refresh" type="button" aria-label="GitHubから更新">↻ 更新</button></header><div class="empty"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M5 4h14v16H5zM8 8h8M8 12h8M8 16h5"/></svg><h3>監視対象はまだありません</h3><p>検証済みIssueが作成されると、labelと関連PRの状態がここに表示されます。</p></div></article>
      <article class="panel chat-panel"><header class="panel-head"><h2>Create</h2><span class="pill">understanding</span></header><div class="chat"><div class="bubble">スマホで回答待ちのジョブが見つけづらいので改善したい</div><div class="state"><span class="dot"></span>default branchと既存Issue / PRを調査します</div><form class="composer"><label for="request" hidden>改善要望</label><input id="request" placeholder="改善したいことを入力…" autocomplete="off"><button class="send" type="submit">送信</button></form><div class="evidence"><details><summary>調査証拠を表示</summary><p>証拠は調査開始後に、sourceとdefault branch SHA付きで表示されます。</p></details></div></div></article>
    </section>
  </main>
  <script>document.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const p=document.querySelector('.pill');p.textContent='investigating';document.querySelector('.state').lastChild.textContent=' repository、コード、Issue、PR、commitを調査しています';});document.querySelector('.refresh').addEventListener('click',e=>{e.currentTarget.textContent='更新済み';setTimeout(()=>e.currentTarget.textContent='↻ 更新',1200)});</script>
</body></html>`;

